language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3

before_install:
    - composer self-update

install:
    - composer install

before_script:
    - Tests/travis/php_setup.sh

script: ./Tests/runTests.sh

after_script:
    - php vendor/bin/coveralls -v

matrix:
    fast_finish: true
